# Generated by Django 5.2.11 on 2026-03-29 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Brief note to user explaining rejection'),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['status'], name='prayer_pray_status_aba343_idx'),
        ),
    ]
