# Generated by Django 5.2.11 on 2026-03-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shouts of Joy Melodies', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='worship/logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='worship/covers/')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worship Team',
                'verbose_name_plural': 'Worship Teams',
            },
        ),
        migrations.CreateModel(
            name='WorshipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('vocalist', 'Vocalist'), ('instrumentalist', 'Instrumentalist')], max_length=20)),
                ('instrument', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='worship/members/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worship_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='worship.worshipteam')),
            ],
            options={
                'verbose_name': 'Worship Team Member',
                'verbose_name_plural': 'Worship Team Members',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='WorshipTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='worship/tracks/')),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='worship/track_covers/')),
                ('youtube_url', models.URLField(blank=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_members', models.ManyToManyField(blank=True, related_name='featured_tracks', to='worship.worshipmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='worship.worshipteam')),
            ],
            options={
                'verbose_name': 'Worship Track',
                'verbose_name_plural': 'Worship Tracks',
                'ordering': ['-released_at', '-created_at'],
            },
        ),
    ]
