# Generated by Django 5.2.11 on 2026-03-01 14:37

from django.db import migrations


def seed_shouts_of_joy_melodies(apps, schema_editor):
    WorshipTeam = apps.get_model("worship", "WorshipTeam")

    # Only seed if no team exists yet
    if WorshipTeam.objects.exists():
        return

    WorshipTeam.objects.create(
        name="Shouts of Joy Melodies",
        tagline="Where Instruments and Voices Unite in Spirit",
        description=(
            "Shouts of Joy Melodies is the official worship team of Spirit Revival Africa. "
            "An independent team operating within the SRA movement, we bring together gifted "
            "instrumentalists and anointed vocalists to usher in the presence of God and "
            "ignite revival through Spirit-filled worship across Africa and beyond."
        ),
        founded_year=2024,
        is_active=True,
    )


def reverse_seed(apps, schema_editor):
    WorshipTeam = apps.get_model("worship", "WorshipTeam")
    WorshipTeam.objects.filter(name="Shouts of Joy Melodies").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_shouts_of_joy_melodies, reverse_seed),
    ]
