# Generated by Django 5.2.11 on 2026-03-01 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0002_seed_shouts_of_joy_melodies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worshipteam',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='WhatsApp group invite link for the team community'),
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('vocalist', 'Vocalist'), ('instrumentalist', 'Instrumentalist')], max_length=20)),
                ('instrument', models.CharField(blank=True, help_text='Required if role is instrumentalist', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Why do you want to join the team?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='worship.worshipteam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worship_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Join Request',
                'verbose_name_plural': 'Team Join Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
