# Generated by Django 5.2.11 on 2026-03-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0003_worshipteam_whatsapp_link_teamjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='worshipteam',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Facebook group link for the team community'),
        ),
    ]
