# Generated by Django 6.0.2 on 2026-02-24 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('book', 'Book (PDF)'), ('journal', 'Journal'), ('mp3_sermon', 'MP3 Sermon'), ('video', 'Video'), ('image', 'Image'), ('wisdom', 'Word of Wisdom'), ('daily_scripture', 'Daily Scripture')], max_length=30)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='content_con_type_2ac35f_idx'), models.Index(fields=['approved'], name='content_con_approve_b12f30_idx'), models.Index(fields=['created_at'], name='content_con_created_29fc54_idx'), models.Index(fields=['category'], name='content_con_categor_9e3022_idx')],
            },
        ),
    ]
