# Generated by Django 6.0.2 on 2026-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('unsplash', 'Unsplash'), ('pexels', 'Pexels'), ('manual', 'Manually Added')], default='unsplash', max_length=20)),
                ('source_id', models.CharField(help_text='ID from the source API', max_length=120, unique=True)),
                ('image_url', models.URLField(max_length=1024)),
                ('thumb_url', models.URLField(blank=True, max_length=1024)),
                ('alt_text', models.CharField(blank=True, max_length=320)),
                ('photographer', models.CharField(blank=True, max_length=200)),
                ('photographer_url', models.URLField(blank=True, max_length=512)),
                ('search_term', models.CharField(blank=True, max_length=120)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fetched Photo',
                'verbose_name_plural': 'Fetched Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='userphoto',
            new_name='content_use_approve_343eb3_idx',
            old_name='ct_uph_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='userphoto',
            new_name='content_use_uploade_0e8093_idx',
            old_name='ct_uph_uploaded_idx',
        ),
        migrations.AddIndex(
            model_name='fetchedphoto',
            index=models.Index(fields=['approved'], name='ct_fph_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchedphoto',
            index=models.Index(fields=['source'], name='ct_fph_source_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchedphoto',
            index=models.Index(fields=['created_at'], name='ct_fph_created_idx'),
        ),
    ]
