# Generated by Django 6.0.2 on 2026-02-27 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_fetch_hero_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Daily Bread', max_length=120)),
                ('verse_reference', models.CharField(help_text='Example: John 3:16-18', max_length=120)),
                ('bible_version', models.CharField(choices=[('KJV', 'King James Version (KJV)'), ('NKJV', 'New King James Version (NKJV)'), ('NIV', 'New International Version (NIV)'), ('ESV', 'English Standard Version (ESV)'), ('NLT', 'New Living Translation (NLT)')], default='KJV', max_length=12)),
                ('verse_text', models.TextField()),
                ('reflection', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-display_date', '-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'display_date'], name='content_dai_is_acti_6bed40_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('story', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='content_sho_is_publ_d9bec2_idx')],
            },
        ),
    ]
