# Generated by Django 5.2.11 on 2026-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_dailybread_shortstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='photo',
            field=models.ImageField(blank=True, help_text='Featured photo (used for Daily Wisdom cards and similar content).', null=True, upload_to='content-photos/'),
        ),
        migrations.AddField(
            model_name='dailybread',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional featured photo displayed alongside this devotional.', null=True, upload_to='daily-bread/'),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional featured image displayed with the story.', null=True, upload_to='short-stories/'),
        ),
        migrations.AlterField(
            model_name='dailybread',
            name='bible_version',
            field=models.CharField(choices=[('KJV', 'King James Version (KJV)'), ('ASV', 'American Standard Version (ASV)'), ('WEB', 'World English Bible (WEB)'), ('DARBY', 'Darby Translation'), ('BBE', 'Bible in Basic English (BBE)'), ('YLT', "Young's Literal Translation (YLT)"), ('NKJV', 'New King James Version (NKJV)'), ('NIV', 'New International Version (NIV)'), ('NIV84', 'New International Version 1984 (NIV84)'), ('ESV', 'English Standard Version (ESV)'), ('NLT', 'New Living Translation (NLT)'), ('NASB', 'New American Standard Bible (NASB)'), ('NASB20', 'New American Standard Bible 2020 (NASB2020)'), ('AMP', 'Amplified Bible (AMP)'), ('AMPC', 'Amplified Bible Classic (AMPC)'), ('MSG', 'The Message (MSG)'), ('CSB', 'Christian Standard Bible (CSB)'), ('HCSB', 'Holman Christian Standard Bible (HCSB)'), ('RSV', 'Revised Standard Version (RSV)'), ('NRSV', 'New Revised Standard Version (NRSV)'), ('GNT', 'Good News Translation (GNT)'), ('CEV', 'Contemporary English Version (CEV)'), ('NCV', 'New Century Version (NCV)'), ('ERV', 'Easy-to-Read Version (ERV)'), ('ICB', "International Children's Bible (ICB)"), ('NET', 'New English Translation (NET)'), ('CJB', 'Complete Jewish Bible (CJB)'), ('TPT', 'The Passion Translation (TPT)'), ('TLB', 'The Living Bible (TLB)'), ('VOICE', 'The Voice Bible')], default='KJV', max_length=12),
        ),
        migrations.AlterField(
            model_name='dailybread',
            name='verse_reference',
            field=models.CharField(help_text='Example: John 3:16-18  — verse text is auto-fetched for KJV / ASV / WEB / DARBY / BBE / YLT. For all other versions enter it manually below.', max_length=120),
        ),
        migrations.AlterField(
            model_name='dailybread',
            name='verse_text',
            field=models.TextField(blank=True, help_text='Auto-populated for supported free translations. For licensed versions (NIV, ESV, NKJV …) type or paste the verse text here.'),
        ),
    ]
