# Generated by Django 5.2.11 on 2026-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contentitem_photo_dailybread_photo_shortstory_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo (JPG / PNG / WEBP).', null=True, upload_to='gallery/photos/')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file (MP4 / MOV / WEBM). Leave blank if using an embed URL instead.', null=True, upload_to='gallery/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube or Vimeo URL (e.g. https://youtu.be/xxxx). Used only when no file is uploaded.', max_length=512)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image shown on the gallery grid for this video.', null=True, upload_to='gallery/thumbs/')),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = displayed first. Use 0 for chronological order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['approved', 'media_type'], name='content_gal_approve_ad540a_idx'), models.Index(fields=['order'], name='content_gal_order_1b8f42_idx')],
            },
        ),
    ]
