# Generated by Django 5.2.11 on 2026-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
