# Generated by Django 5.2.11 on 2026-03-29 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_gallery_approved_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstory',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Admin-created stories default to approved. User submissions default to pending.', max_length=20),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='Set when submitted by a registered user (not admin-created).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shortstory',
            index=models.Index(fields=['status'], name='content_sho_status_55717d_idx'),
        ),
    ]
