# Generated by Django 5.2.11 on 2026-03-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
