# Generated by Django 5.2.11 on 2026-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipleship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
