# Generated by Django 6.0.2 on 2026-02-24 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevivalHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('meeting_schedule', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_hubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hubs.revivalhub')),
            ],
        ),
        migrations.AddIndex(
            model_name='revivalhub',
            index=models.Index(fields=['status'], name='hubs_reviva_status_97cedd_idx'),
        ),
        migrations.AddIndex(
            model_name='revivalhub',
            index=models.Index(fields=['country', 'city'], name='hubs_reviva_country_8ca5cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hubmembership',
            unique_together={('user', 'hub')},
        ),
    ]
